"""Add chart table

Revision ID: 5576eb54747d
Revises: adcccfe29728
Create Date: 2025-05-02 20:30:30.348420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5576eb54747d'
down_revision: Union[str, None] = 'adcccfe29728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_datetime', sa.DateTime(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_birth_datetime'), 'chart', ['birth_datetime'], unique=False)
    op.create_index(op.f('ix_chart_city'), 'chart', ['city'], unique=False)
    op.create_index(op.f('ix_chart_id'), 'chart', ['id'], unique=False)
    op.create_index(op.f('ix_chart_location_name'), 'chart', ['location_name'], unique=False)
    op.create_index(op.f('ix_chart_name'), 'chart', ['name'], unique=False)
    op.create_index(op.f('ix_chart_user_id'), 'chart', ['user_id'], unique=False)
    op.drop_index('ix_user_id', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.drop_index(op.f('ix_chart_user_id'), table_name='chart')
    op.drop_index(op.f('ix_chart_name'), table_name='chart')
    op.drop_index(op.f('ix_chart_location_name'), table_name='chart')
    op.drop_index(op.f('ix_chart_id'), table_name='chart')
    op.drop_index(op.f('ix_chart_city'), table_name='chart')
    op.drop_index(op.f('ix_chart_birth_datetime'), table_name='chart')
    op.drop_table('chart')
    # ### end Alembic commands ###
